name: tek_generator
description: An resource class generator for Flutter, like Android resource class R.
version: 1.2.0
repository: https://github.com/anhquan7826/tek_generator

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

executables:
  generate:

environment:
  sdk: ^3.3.3

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
